# Generated by Django 2.0.3 on 2018-03-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='xate',
            new_name='date',
        ),
    ]
