# Generated by Django 2.0.3 on 2018-04-16 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180322_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='lacations',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
