# Generated by Django 2.0.3 on 2018-04-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='gambar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
